DROP TABLE line_of_tech;

CREATE TABLE line_of_tech (L_ID NUMBER(7) CONSTRAINT L_PK PRIMARY KEY, L_NAME VARCHAR2(30) CONSTRAINT L_NN NOT NULL);

COMMIT;

DROP TABLE faculty;

CREATE TABLE faculty (F_ID NUMBER(7) CONSTRAINT F_PK PRIMARY KEY, F_NAME VARCHAR2(30) CONSTRAINT F_NN NOT NULL, L_ID NUMBER(7), CONSTRAINT F_FK FOREIGN KEY(L_ID) REFERENCES LINE_OF_TECH (L_ID));

COMMIT;

DROP TABLE BATCH;

CREATE TABLE BATCH (B_ID NUMBER(7) CONSTRAINT B_PK PRIMARY KEY, B_NAME VARCHAR2(30) CONSTRAINT B_NN NOT NULL, START_DATE DATE, END_DATE DATE,F_ID NUMBER(7), CONSTRAINT B_FK FOREIGN KEY(F_ID) REFERENCES FACULTY (F_ID));

COMMIT;

DROP TABLE EMP_TABLE;

CREATE TABLE EMP_TABLE (E_ID NUMBER(7) CONSTRAINT E_PK PRIMARY KEY, 
E_NAME VARCHAR2(30) CONSTRAINT E_NN NOT NULL, 
DESIGNATION VARCHAR2(30)
 CONSTRAINT D_CHK CHECK(DESIGNATION='ASST S/W ENGINEER' OR DESIGNATION='S/W ENGINEER '),
 QUALIFICATION VARCHAR2(10) CONSTRAINT Q_CHK CHECK (QUALIFICATION='BSC.IT' OR  QUALIFICATION='B.E' OR QUALIFICATION='MCA' ), B_ID NUMBER(7), CONSTRAINT E_FK FOREIGN KEY(B_ID) REFERENCES BATCH (B_ID));


COMMIT;

DROP TABLE COURSE;

CREATE TABLE  COURSE (C_ID NUMBER(7) CONSTRAINT C_PK PRIMARY KEY, C_NAME VARCHAR2(30) CONSTRAINT C_NN NOT NULL,E_ID NUMBER(7),B_ID NUMBER(7),L_ID NUMBER(7) ,F_ID NUMBER(7),CONSTRAINT CF_FK FOREIGN KEY(F_ID) REFERENCES FACULTY (F_ID),CONSTRAINT CB_FK FOREIGN KEY(B_ID) REFERENCES BATCH (B_ID),CONSTRAINT CL_FK FOREIGN KEY(L_ID) REFERENCES LINE_OF_TECH (L_ID),CONSTRAINT CE_FK FOREIGN KEY(E_ID) REFERENCES EMP_TABLE (E_ID));

COMMIT;

DROP TABLE TEST;

CREATE TABLE  TEST (T_ID NUMBER(7) CONSTRAINT T_PK PRIMARY KEY, TEST_DATE DATE, E_ID NUMBER(7),B_ID NUMBER(7), C_ID NUMBER(7),CONSTRAINT TB_FK FOREIGN KEY(B_ID) REFERENCES BATCH (B_ID),CONSTRAINT TE_FK FOREIGN KEY(E_ID) REFERENCES EMP_TABLE (E_ID),CONSTRAINT TC_FK FOREIGN KEY(C_ID) REFERENCES COURSE (C_ID));

COMMIT; 

--select constraint_name, constraint_type from user_constraints where table_name = 'TEST';

DROP TABLE MODULE;

CREATE TABLE MODULE (M_ID VARCHAR2(5) CONSTRAINT M_PK PRIMARY KEY, T_ID NUMBER(7), E_ID NUMBER(7), MTT NUMBER(2), MPT NUMBER(2), ASSIGNMENT NUMBER(2), CONSTRAINT ME_FK FOREIGN KEY(E_ID) REFERENCES EMP_TABLE (E_ID), CONSTRAINT MT_FK FOREIGN KEY(T_ID) REFERENCES TEST (T_ID));

COMMIT;

DROP TABLE DQS;

CREATE TABLE DQS (C_ID NUMBER(7), E_ID NUMBER(7), M_ID VARCHAR2(5), DQ1 NUMBER(3), DQ2 NUMBER(3), DQ3 NUMBER(3), CONSTRAINT DC_FK FOREIGN KEY(C_ID) REFERENCES COURSE (C_ID), CONSTRAINT DE_FK FOREIGN KEY(E_ID) REFERENCES EMP_TABLE (E_ID), CONSTRAINT DM_FK FOREIGN KEY(M_ID) REFERENCES MODULE (M_ID));

COMMIT;


